<template>
  <div class="home-TUIKit-main">
      <div :class="env?.isH5 ? 'conversation-h5' : 'conversation'"
          v-show="!env?.isH5 || currentModel === 'conversation'">
          <TUISearch class="search" />
          <TUIConversation @current="handleCurrentConversation" />
      </div>
      <div class="chat" v-show="!env?.isH5 || currentModel === 'message'">
          <TUIChat>
              <h1>欢迎使用腾讯云即时通信IM</h1>
          </TUIChat>
      </div>
  </div>
</template>


<script lang="ts">
import { defineComponent, reactive, toRefs, getCurrentInstance,onMounted } from 'vue';
import { TUIEnv } from '../../TUIKit/TUIPlugin';
import { TUIComponents, TUICore, genTestUserSig } from '../../TUIKit';
import {useRoute} from 'vue-router'
export default defineComponent({
  name: 'contactme',
  setup() {
      let route:any=useRoute().query.name
      console.log(route+'route');
      
      const data = reactive({
          env: TUIEnv(),
          currentModel: 'conversation',
      });
      const handleCurrentConversation = (value: string) => {
          data.currentModel = value ? 'message' : 'conversation';
      };
     
      
      onMounted(() => {
      const SDKAppID = 1400794502; // Your SDKAppID
      const secretKey = '07f372761bb1415572cbe149b5d38af2207b1b1077ed8f91184a7a8b574ebf21'; //Your secretKey
      const userID = route; // User ID
      const TUIins = TUICore.instance
      console.log("app内取instance是否与main中的绝对相同", TUICore.instance === getCurrentInstance()?.appContext.config.globalProperties.$TUIKit)
      // login TUIKit
        TUIins.logout()
        TUIins.login({
          userID ,
          userSig: genTestUserSig({
              SDKAppID,
              secretKey,
              userID,
          }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
      });
      })
      console.log( 'sig是'+genTestUserSig({
              SDKAppID:1400794502,
              secretKey:'07f372761bb1415572cbe149b5d38af2207b1b1077ed8f91184a7a8b574ebf21',
              userID:'mall',
          }).userSig);
      

      return {
          ...toRefs(data),
          handleCurrentConversation,
      };
  },
});
</script>

<style scoped>
.home-TUIKit-main {
  display: flex;
  height: 100vh;
  overflow: hidden;
}

.search {
  padding: 12px;
}

.conversation {
  min-width: 285px;
  flex: 0 0 24%;
  border-right: 1px solid #f4f5f9;
}

.conversation-h5 {
  flex: 1;
  border-right: 1px solid #f4f5f9;
}

.chat {
  flex: 1;
  height: 100%;
  position: relative;
}
</style>